# Constrained Pressure Vessel

## Set Up Virtual Environment
The following creates a virtual environment folder for this project, sets it up correctly, and activates the virtual environment.

In [1]:
import os
venvExists = os.path.isdir('venv')
if venvExists is False:
    os.mkdir("venv")
    os.system("python -m venv venv")
    os.system("pip install -r requirements.txt")
os.system(r"venv\Scripts\activate")

import numpy as np
import matplotlib.pyplot as plt

## Functions

In [34]:
def get_DeltaR(R_i, R_o):
    return R_o-R_i

def get_sigma_rr(R, P_i, P_o, R_i, R_o, DeltaR):
    lhs = P_o*(R_i-R)
    rhs = P_i*(-R_o+R)
    sigma_rr = (lhs + rhs)/(DeltaR)
    # print(f"sigma_rr = {sigma_rr}")
    return sigma_rr

def get_sigma_tt(R, P_i, P_o, R_i, R_o, DeltaR):
    lhs = P_o*(R_i+R)
    rhs = P_i*(R_o+R)
    sigma_tt = (lhs - rhs)/(DeltaR)
    # print(f"sigma_tt = {sigma_tt}")
    return sigma_tt

def get_sigma_zz(R, P_i, P_o, R_i, R_o, DeltaR, nu):
    lhs = P_o*R_i
    rhs = P_i*R_o
    sigma_zz = (2*nu*(lhs - rhs))/(DeltaR)
    # print(f"sigma_zz = {sigma_zz}")
    return sigma_zz

def get_tensor(R, P_i, P_o, R_i, R_o, nu):
    DeltaR = get_DeltaR(R_i=R_i, R_o=R_o)
    sigma_rr = get_sigma_rr(R, P_i, P_o, R_i, R_o, DeltaR)
    sigma_tt = get_sigma_tt(R, P_i, P_o, R_i, R_o, DeltaR)
    sigma_zz = get_sigma_zz(R, P_i, P_o, R_i, R_o, DeltaR, nu)
    tensor_o = np.asarray([[sigma_rr,           0.0,                   0.0],
                          [0.0,           sigma_tt,                   0.0],
                          [0.0,                      0.0,        sigma_zz]])/1E6 # MPa
    print(f'\ntensor @ (r = {R**(1/-2):.3f} m) =')
    print(np.round(tensor_o,3))


def get_TWPV_tensor(P_i, P_o, r, t):
    DeltaP = (P_i-P_o)
    print(t)
    tensor = np.asarray([[0.0,           0.0,                   0.0],
                          [0.0,           (DeltaP*r)/t,                   0.0],
                          [0.0,                      0.0,        (DeltaP*r)/(2*t)]])/1E6 # MPa
    print(f'\n thin walled pressure vessel tensor =')
    print(np.round(tensor,3))

## Main Section
You can change the:
- $L$ - Length of the billet [m]
- $b$ - Width/breadth of the billet [m]
- $h$ - Height of the billet [m]
- $k$ - Shear yield strength [Pa]
- $\mu$ - Coefficient of friction between $0-1$
To normalise the stress set `normY` to `True`.

In [35]:
P_o = 0.1E6 # in Pa
P_i = 1.5E6 # in Pa
r_o = 0.1
r_i = 0.1-2E-3
R_o = (r_o)**(-2) # in m^-2
R_i = (r_i)**(-2) # in m^-2
DeltaR = R_o-R_i
nu = 0.25
R = R_i
get_tensor(R_i, P_i, P_o, R_i, R_o, nu)

get_tensor(R_o, P_i, P_o, R_i, R_o, nu)


tensor @ (r = 0.098 m) =
[[-1.5    0.     0.   ]
 [ 0.    69.207  0.   ]
 [ 0.     0.    16.927]]

tensor @ (r = 0.100 m) =
[[-0.1    0.     0.   ]
 [ 0.    67.807  0.   ]
 [ 0.     0.    16.927]]


In [37]:
print('Thin walled pressure vessel:')
t = 2E-3
get_TWPV_tensor(P_i, P_o, r=r_i, t=t)

Thin walled pressure vessel:
0.002

 thin walled pressure vessel tensor =
[[ 0.   0.   0. ]
 [ 0.  68.6  0. ]
 [ 0.   0.  34.3]]
